pip install numpy 

In [5]:
import numpy as np

# 1. numpy 创建

In [7]:
# 一维
np.array([1,2,3])

array([1, 2, 3])

In [8]:
# 二维
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [2]:
# 三维
a = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(a.shape)
print(a)

(2, 2, 3)
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [3]:
# 特殊值创建
print(np.ones((4,5)))
print(np.zeros((3,4)))

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
a = np.array([[4,2,3],[6,7,8]])
print(np.ones_like(a)) # 以相同的shape生成一个全1矩阵
print(np.zeros_like(a)) # 以相同的shape生成一个全0矩阵

[[1 1 1]
 [1 1 1]]
[[0 0 0]
 [0 0 0]]


In [4]:
print(np.arange(15))
print(np.arange(3,15,2))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[ 3  5  7  9 11 13]


In [14]:
print(np.eye(3)) # 单位矩阵

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# 2. numpy 基本使用

In [15]:
a = np.array([[1,2,3,4],[4,5,6,7],[7,8,9,10]])
print(a.ndim) # 获取矩阵维度
print(a.shape) # 获取矩阵大小
print(a)
print(a.T) # 矩阵转置

2
(3, 4)
[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]
[[ 1  4  7]
 [ 2  5  8]
 [ 3  6  9]
 [ 4  7 10]]


In [18]:
a = np.array([[1,2,3],[4,5,6]])
print(a)

print('reshape:')
print(a.reshape(3,2)) # 修改矩阵形状, 与转置不同

print('transpose:')
print(a.T)

[[1 2 3]
 [4 5 6]]
reshape:
[[1 2]
 [3 4]
 [5 6]]
transpose:
[[1 4]
 [2 5]
 [3 6]]


# 3. numpy 数据类型
* int8, uint8         有／无符号的8位整型
* int16, uint16     有／无符号的16位整型
* int32, uint32   有／无符号的32位整型
* int64, uint64       有／无符号的64位整型
* float16                  半精度浮点数
* float32           标准的单精度浮点数，与C的float兼容。
* float64           标准的双精度浮点数。与C的double和Python的float兼容。
* float128 g          扩展精度浮点数
* complex64/128/256 -c8/16/32  分别用两个32位，64位或128位浮点数表示的复数。
* bool                  存储True和False值的布尔类型
* object                   Python对象类型
* string_                 固定长度的字符串类型。S10代表长度为10的字符串。
* unicode_                固定长度的unicode类型

In [6]:
a1 = np.array([[1,2,3],[4,5,6]])
print(a1, a1.dtype)

a1[0,0] = 1.5
print(a1, a1.dtype)

a1 = a1 * 1.5
print(a1, a1.dtype)

[[1 2 3]
 [4 5 6]] int64
[[1 2 3]
 [4 5 6]] int64
[[1.5 3.  4.5]
 [6.  7.5 9. ]] float64


In [9]:
a2 = np.array([[1,2,3],[4,5,6]], dtype='float32')
print(a2, a2.dtype)

a2[0,0] = 1.5
print(a2, a2.dtype)

[[1. 2. 3.]
 [4. 5. 6.]] float32
[[1.5 2.  3. ]
 [4.  5.  6. ]] float32


In [10]:
a3 = np.array([1.2,2.4,3.7])
print(a3, a3.dtype)

a3 = a3.astype(np.int)
print(a3, a3.dtype)

[1.2 2.4 3.7] float64
[1 2 3] int64


# 4. numpy 常用计算

In [12]:
x = np.array([1,2,3])
y = np.array([3,6,7])
print(x + y)
print(x * y)
print(x + 2)
print(x * 2)

[ 4  8 10]
[ 3 12 21]
[3 4 5]
[2 4 6]


In [28]:
# 三角函数
pi = 3.14159265359
x = np.array([0,0.5*pi,1*pi,1.5*pi])
y = np.array([1,0,-1])

print(np.sin(x))
print(np.cos(x))
print(np.tan(x))

print(np.arcsin(y))
print(np.arccos(y))
print(np.arctan(y))

[ 0.00000000e+00  1.00000000e+00 -2.06823107e-13 -1.00000000e+00]
[ 1.00000000e+00 -1.03411554e-13 -1.00000000e+00  3.10678750e-13]
[ 0.00000000e+00 -9.67009938e+12  2.06823107e-13 -3.21875893e+12]
[ 1.57079633  0.         -1.57079633]
[0.         1.57079633 3.14159265]
[ 0.78539816  0.         -0.78539816]


In [29]:
a = np.array([0,1,2,3,4])
print(np.sqrt(a)) # 开根号
print(np.exp(a)) # 指数运算 e^x
print(a ** 2) # 平方

[0.         1.         1.41421356 1.73205081 2.        ]
[ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
[ 0  1  4  9 16]


In [34]:
# 获取最大值
a = np.array([1,2,3,4])
b = np.array([3,1,9,2])
print(np.maximum(a,b))

[3 2 9 4]


## 5. 矩阵乘法

In [19]:
a1 = np.array([[1,2,3],[3,4,5]]) # 2x3矩阵
a2 = np.array([[4,5],[6,7],[8,9]]) # 3x2矩阵
if (a1.shape[1] == a2.shape[0]): # 判断矩阵乘法条件
    print(a1.dot(a2)) # 注意与 * 区分

[[40 46]
 [76 88]]


In [20]:
x1 = np.array([[1,2],[3,4]])
x2 = np.array([[1,2],[3,4]])
print(x1 * x2)
print(x1.dot(x2))

[[ 1  4]
 [ 9 16]]
[[ 7 10]
 [15 22]]


In [21]:
# 求逆矩阵
a = np.array([[1,2],[3,4]])
inv_a = np.linalg.inv(a)
print(a)
print(inv_a)
print(a.dot(inv_a))

[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[[1.0000000e+00 0.0000000e+00]
 [8.8817842e-16 1.0000000e+00]]


In [35]:
# 最大/小值
a = np.array([[1,5,3],[4,2,6]])
print(a.min())
print(a.max())

# 每列最小值, axis=0 对行(第0维)进行比较
print(a.min(axis=0)) 
# 每行最大值 axis=1 对列(第1维)进行比较
print(a.max(axis=1)) 
# 获取每行最大数值所在位置 
print(a.argmax(axis=1))

1
6
[1 2 3]
[5 6]
[1 2]


In [23]:
# 平均值
a = np.array([[1,3,6],[2,5,7]])
print(a.mean())
print(a.mean(axis=0)) # 计算每列平均值
print(a.mean(axis=1)) # 计算每行平均值

4.0
[1.5 4.  6.5]
[3.33333333 4.66666667]


In [24]:
# 方差
# 相当于 np.mean(np.abs(x - x.mean())**2)
a = np.array([[1,2,3],[4,5,6]])
print(a.var()) 
print(a.var(axis=0)) # 计算每行方差
print(a.var(axis=1)) # 计算每列方差

2.9166666666666665
[2.25 2.25 2.25]
[0.66666667 0.66666667]


In [25]:
# 标准差
# 相当于 np.sqrt(np.mean(np.abs(x - x.mean())**2))
a = np.array([[1,2,3],[4,5,6]])
print(a.std())
print(a.std(axis=0))
print(a.std(axis=1))

1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [26]:
# 求和
a = np.array([[1,2,3],[4,5,6]])
print(a.sum())
print(a.sum(axis=0))
print(a.sum(axis=1))

21
[5 7 9]
[ 6 15]


In [27]:
# 去重
a = np.array([1,2,1,4,2,3])
print(np.unique(a))

[1 2 3 4]


# 5. 矩阵截取 & 合并

In [39]:
# 行列截取
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('a.shape:', a.shape)
print(a)
print()
print(a[:2,:]) # 获取前2行 : 2维
print(a[:,-2:]) # 获取后2列 ： 2维
print(a[0,:]) # 获取第0行 : 1维
print(a[:,2]) # 获取第2行 : 1维
print(a[1,2]) # 获取第二行，第三列的数值 ： 数值

a.shape: (3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[1 2 3]
 [4 5 6]]
[[2 3]
 [5 6]
 [8 9]]
[1 2 3]
[3 6 9]
6


In [45]:
# 条件截取
b = np.array([3,1,9,2,3])
c = b.copy()

# 数组中大于2的数的值
print('---------- b>2 ----------')
print(b>2)
print('--------- b[b>2] ---------')
print(b[b>2])

# 数组中大于2的数的序号
index = np.where(b>2)
print(index)

# 将数组中大于2的数变为0
b[index] = 0
print(b)
c[c>2] = 0
print(c)

---------- b>2 ----------
[ True False  True False  True]
--------- b[b>2] ---------
[3 9 3]
(array([0, 2, 4]),)
[0 1 0 2 0]
[0 1 0 2 0]


In [46]:
# 矩阵合并
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[10,11,12]])

# 横向合并
print(np.hstack([a1,a2]))

# 纵向合并
print(np.vstack([a1,a2]))

[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
